### ISSUE TITLE
Nem elég gyors

### ISSUE THREAD

**Issue by MrGazdag** [Remarci225/PrimeX#1]
az érettségi visszaszámláló gyorsabban jelenít meg prímszámokat mint ez xd

**Comment by Remarci225** [comment]
Való igaz, de már probléma megoldva :D

**Comment by MrGazdag** [comment]
Elfelejtettél commitolni/pusholni, igaz? :D

**Comment by Remarci225** [comment]
Nem, fel lett rakva minden :)

**Comment by MrGazdag** [comment]
Mármint arra gondolok, hogy megcsináltad a repot 11 hónapja, és nem volt kontent rajta amikor írtam az issuet, tehát gondolom elfelejtettél 11 hónapja pusholni, illetve, mivel a commit is mostani dátummal rendelkezik, ezért commitolni is :D

**Comment by Remarci225** [comment]
Ja, értem. Nem, nem felejtettem el, inkább arról volt szó, hogy megcsináltam a repot, elkezdtem írni a programot, de nem jutottam el vele odáig, hogy érdemes legyen push-t/commitot csinálni. Aztán telt az idő, megpróbáltam megírni több nyelven is, hogy lehessen valahogy összehasonlítani őket, de mivel eredetileg egy robosztusabb programot terveztem, (és nem gondoltam, hogy bárki rátalál erre a projektre ;) ) ezért nem gondoltam, hogy érdemes felrakni a kódokat ilyen állapotban, aztán meg inkább más foglalt le és nemigen dolgoztam rajta azóta.

**Comment by MrGazdag** [comment]
Mindegy, én csak viccesnek tartottam hogy "Villámgyors prímszámkereső" néven nem igazán írt ki prímeket :D

**Comment by Remarci225** [comment]
Igen, ironikus, bár az igaz, hogy így gyorsabban lefut, mintha keresne is prímeket ;)
